server:
  port: 4004

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_HOST:6379}
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.burstCapacity: 5
            redis-rate-limiter.replenishRate: 5
            key-resolver: "#{@ipKeyResolver}"
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth,/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://patient-service:8081
          predicates:
            - Path=/api/patients,/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: patient-service-api-docs
          uri: http://patient-service:8081
          predicates:
            - Path=/api-docs/patients/**
          filters:
            - RewritePath=/api-docs/patients(?<segment>/?.*),/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
