server:
  port: 4004

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:8081
          predicates:
            - Path=/api/patients,/api/patients/**
          filters:
            - StripPrefix=1

        - id: patient-service-api-docs
          uri: http://patient-service:8081
          predicates:
            - Path=/api-docs/patients/**
          filters:
            - RewritePath=/api-docs/patients(?<segment>/?.*),/v3/api-docs${segment}
